node {
	def app

	stage('Clone repository') {
    	  checkout([$class: 'GitSCM', branches: [[name: '*/master']],
    	  doGenerateSubmoduleConfigurations: false, extensions: [],
    	  submoduleCfg: [], userRemoteConfigs:
    	  [[credentialsId: 'gitlab-repo-creds',
    	  url: 'git@gitlab-selfhosted.org:test-group/docker-image-file.git']]])
	}

	stage('Build image') {
    	  app = docker.build("docker-image")
	}

	stage('Test image') {
       	  sh '''
       	  if ! docker inspect docker-image &> /dev/null; then
            echo 'docker-image does not exist!'
            exit 1
       	  fi
       	  '''
	}

	stage('Push image') {
    	  echo 'Push image'
    	  docker.withRegistry('https://local-registry:9666', 'registry-creds') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
    	  }
	}

	stage('Clean existing image') {
  	  sh "docker rmi docker-image"
	}
}
